### ISSUE TITLE
Corpus button

### ISSUE THREAD

**Issue by calhound** [BCDigSchol/missionary-grammars#13]
Would it make more sense to have the 'corpus' button on the home page lead to the 'texts' page, rather than to the carousel? the carousel becomes visible without the need for a button if you read the entire introduction, and since it is more of a display tool, it doesn't really fulfill the expectation of 'corpus' in the sense of a (whole) collection of texts.

**Comment by annakijas1** [comment]
That can be easily swapped out.

**Comment by annakijas1** [comment]
Changed path to go to texts not carousel.
