### ISSUE TITLE
Elastic search issue

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/missionary-grammars#17]
Error message when any text is selected. See [example](http://corpus-missionnaire.bc.edu/texts/1).

**Comment by annakijas1** [comment]
@Otterfan This was working as of yesterday, but today (2/14) we are getting a different error message. 

<img width="1033" alt="screen shot 2018-02-14 at 11 06 29 am" src="https://user-images.githubusercontent.com/6841932/36214289-20c9f5f8-1177-11e8-9f6a-431a7b0ebfd8.png">

**Comment by Otterfan** [comment]
Sorry, we had a reboot due to Spectre/Meltdown that I thought was happening tomorrow @ 2am instead of today @ 2am. It's up now.

**Comment by annakijas1** [comment]
Phew!! Thanks!
