### ISSUE TITLE
Lighten home page image slightly?

### ISSUE THREAD

**Issue by calhound** [BCDigSchol/missionary-grammars#8]
Can we lighten the background image on the home page a fraction? I agree it needs to be darker to allow for contrast with the title/subtitle, but can the color be lifted slightly?

**Comment by Otterfan** [comment]
I've split the difference on the shade. Does it look better?

**Comment by annakijas1** [comment]
Looks better. Keep in mind that the shade will appear slightly different across screens, due to people's individual settings.
